### ISSUE TITLE
Sitecore 7.1 - Auto-publishing of synced items fails

### ISSUE THREAD

**Issue by afaniuolo** [kamsar/Unicorn#180]
_ERROR: Method not found: 'Void Sitecore.Publishing.Publisher..ctor(Sitecore.Publishing.PublishOptions, System.Collections.Generic.IEnumerable`1)'. (System.MissingMethodException)
at Unicorn.Publishing.ManualPublishQueueHandler.PublishQueuedItems(Item triggerItem, Database[] targets, IProgressStatus progress)
at Unicorn.Pipelines.UnicornSyncEnd.TriggerAutoPublishSyncedItems.Process(UnicornSyncEndPipelineArgs args)
at (Object , Object[] )
at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
at Unicorn.ControlPanel.Pipelines.UnicornControlPanelRequest.SyncVerb.Process(IProgressStatus progress, ILogger additionalLogger)_

Looking at the code in ManualPublishQueueHandler.cs (https://github.com/kamsar/Unicorn/blob/master/src/Unicorn/Publishing/ManualPublishQueueHandler.cs - line 37), the Publisher.PublishWithResults() method in Sitecore.Kernel is not implemented in Sitecore 7.1. The method is implemented starting in Sitecore 7.2.

**Comment by kamsar** [comment]
Correct, this is a known issue that I am not intending to fix. Unicorn uses publishing APIs introduced in Sitecore 7.2.

Disable the auto publish configuration file when using it with 7.1 and earlier.
