### ISSUE TITLE
Transparent Sync - startIndex cannot be larger than length of string

### ISSUE THREAD

**Issue by cubeberg** [kamsar/Unicorn#184]
[RainbowSerializationError.zip](https://github.com/kamsar/Unicorn/files/539116/RainbowSerializationError.zip)
Sitecore 8.2, Unicorn 3.2.0.  
Just starting to set up Unicorn on a new solution.  I was able to perform an initial sync.  I enabled Transparent sync, but ran into an error when adding an item with a name shorter than 6 characters.

4668 17:00:56 ERROR Failed to add the item version. Item ID: {EA8682FF-9276-42E0-A373-A81D91ECCEB9}, database: master, language: en
Exception: System.ArgumentOutOfRangeException
Message: startIndex cannot be larger than length of string.
Parameter name: startIndex
Source: mscorlib
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Rainbow.Storage.SerializationFileSystemTree.GetTargetPhysicalPath(IItemData item)
   at Rainbow.Storage.SerializationFileSystemTree.Save(IItemData item)
   at Unicorn.Data.DataProvider.UnicornDataProvider.SaveItem(ItemDefinition itemDefinition, ItemChanges changes, CallContext context)
   at Unicorn.Data.DataProvider.UnicornSqlServerDataProvider.SaveItem(ItemDefinition itemDefinition, ItemChanges changes, CallContext context)
   at Sitecore.Data.DataProviders.DataProvider.SaveItem(ItemDefinition item, ItemChanges changes, CallContext context, DataProviderCollection providers)
   at Sitecore.Data.DataSource.SaveItem(ID itemID, ItemChanges changes)
   at Sitecore.Data.Engines.EngineCommand`2.Execute()
   at Sitecore.Data.Engines.DataEngine.SaveItem(Item item)
   at Sitecore.Data.Managers.ItemProvider.SaveItem(Item item)
   at Sitecore.Data.Managers.DefaultItemManager.ExecuteAndReturnResult[TArgs,TResult](String pipelineName, String pipelineDomain, Func`1 pipelineArgsCreator, Func`1 fallbackResult)
   at Sitecore.Data.Managers.DefaultItemManager.SaveItem(Item item)
   at Sitecore.Nexus.Data.DataCommands.AddVersionCommand.Execute(Item item)
   at Sitecore.Data.Engines.EngineCommand`2.Execute()
   at Sitecore.Data.Engines.DataEngine.AddVersion(Item item)

If it's applicable, I've configured Sitecore for Solr and installed WFFM.
Unicorn and Rainbow configuration attached.  Serialized files are outside of the website so they end up in source control.

[RainbowSerializationError.zip](https://github.com/kamsar/Unicorn/files/537349/RainbowSerializationError.zip)

**Comment by cubeberg** [comment]
I did test today - this only occurs when I use a lower path (~/../Unicorn breaks - /Unicorn works fine)

**Comment by cubeberg** [comment]
That did it - thank you!
