### ISSUE TITLE
ArgumentException: An item with the same key has already been added.

### ISSUE THREAD

**Issue by MrSnappingTurtle** [kamsar/Unicorn#206]
Hi,

We're on Sitecore 7.5 and recently updated to Unicorn 3.3.2. The upgrade went smooth for all but one machine (at least so far). Every time I try to sync, I get the following error. It seems to mostly affect "Media Library" and "Globals" items as I haven't seen any "Renderings" or "Templates" featured. Anything that we should look at that might be causing this?

```
master:/sitecore/content/globals/path/to/item (de7654f3-6c6c-43cc-824c-1445eaa89776)
C:\path\to\item.yml
> ArgumentException: An item with the same key has already been added.
```

The log has stack traces like the following:

```
...

INNER EXCEPTION
master:/sitecore/media library/company/full/product-com/rendering-thumbnails (aa1c1603-57dc-47c3-908b-94aca397b0f3) (Rainbow.Storage.Sc.Deserialization.DeserializationException)
No stack trace available.
INNER EXCEPTION
An item with the same key has already been added. (System.ArgumentException)
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Rainbow.Diff.ItemComparer.CompareInternal(IItemData sourceItem, IItemData targetItem, Boolean abortOnChangeFound)
   at Unicorn.Evaluators.SerializedAsMasterEvaluator.ShouldUpdateExisting(IItemData sourceItem, IItemData targetItem, DeferredLogWriter`1 deferredUpdateLog)
   at Unicorn.Evaluators.SerializedAsMasterEvaluator.EvaluateUpdate(IItemData sourceItem, IItemData targetItem)
   at Unicorn.Loader.SerializationLoader.DoLoadItem(IItemData serializedItemData, IConsistencyChecker consistencyChecker)
   at Unicorn.Loader.DeserializeFailureRetryer.RetryAll(ISourceDataStore sourceDataStore, Action`1 retrySingleItemAction, Action`1 retryTreeAction)


INNER EXCEPTION
master:/sitecore/media library/company/full/product-com/components/callout (6c4115b9-8c83-4158-84e7-69b7028a6b80) (Rainbow.Storage.Sc.Deserialization.DeserializationException)
No stack trace available.
INNER EXCEPTION
An item with the same key has already been added. (System.ArgumentException)
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Rainbow.Diff.ItemComparer.CompareInternal(IItemData sourceItem, IItemData targetItem, Boolean abortOnChangeFound)
   at Unicorn.Evaluators.SerializedAsMasterEvaluator.ShouldUpdateExisting(IItemData sourceItem, IItemData targetItem, DeferredLogWriter`1 deferredUpdateLog)
   at Unicorn.Evaluators.SerializedAsMasterEvaluator.EvaluateUpdate(IItemData sourceItem, IItemData targetItem)
   at Unicorn.Loader.SerializationLoader.DoLoadItem(IItemData serializedItemData, IConsistencyChecker consistencyChecker)
   at Unicorn.Loader.DeserializeFailureRetryer.RetryAll(ISourceDataStore sourceDataStore, Action`1 retrySingleItemAction, Action`1 retryTreeAction)


INNER EXCEPTION
master:/sitecore/media library/company/full/product-com/components/callout2 (a585c27e-af68-4698-ac2a-6d091e821f9c) (Rainbow.Storage.Sc.Deserialization.DeserializationException)
No stack trace available.
INNER EXCEPTION
An item with the same key has already been added. (System.ArgumentException)
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Rainbow.Diff.ItemComparer.CompareInternal(IItemData sourceItem, IItemData targetItem, Boolean abortOnChangeFound)
   at Unicorn.Evaluators.SerializedAsMasterEvaluator.ShouldUpdateExisting(IItemData sourceItem, IItemData targetItem, DeferredLogWriter`1 deferredUpdateLog)
   at Unicorn.Evaluators.SerializedAsMasterEvaluator.EvaluateUpdate(IItemData sourceItem, IItemData targetItem)
   at Unicorn.Loader.SerializationLoader.DoLoadItem(IItemData serializedItemData, IConsistencyChecker consistencyChecker)
   at Unicorn.Loader.DeserializeFailureRetryer.RetryAll(ISourceDataStore sourceDataStore, Action`1 retrySingleItemAction, Action`1 retryTreeAction)

...
```

**Comment by kamsar** [comment]
That suggests to me you might have corrupted yaml file.

The relevant code is this:
```
var sourceUnversioned = sourceItem.UnversionedFields.ToDictionary(value => value.Language.Name);			var targetUnversioned = targetItem.UnversionedFields.ToDictionary(value => value.Language.Name);
```

The only way the same key would be added twice is if the UnversionedFields collection had _two_ entries for a given language. Check your YAML file and make sure there aren't two duplicate language headers.

**Comment by MrSnappingTurtle** [comment]
I checked the files and don't see any duplicate headers:

```
---
ID: "6a4adf5d-d20a-47d4-ad19-690c46662114"
Parent: "2d0b90fb-fa1f-49bb-9d01-15ad1b0f5e3b"
Template: "65fbca53-1161-4978-9d91-fc4a1c1501ad"
Path: "/sitecore/content/globals/full/product-com/callouts/some-information"
DB: master
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: some Information
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160620T140032
    - ID: "c90e6435-280f-45de-b3b5-f59fab5218ce"
      Hint: Link
      Value: |
        <link linktype="javascript" text="some Information" url="javascript:trackActivity('xyz'); window.open('http://Company.com/united_states/product/product_english.pdf')" anchor="" />
```

However, if the yaml was corrupt, it doesn't make sense why I was the only one of three machines that had the issue. 

The good news is that your comment reminded me that the other machines had the "Languages" wiped under core and master with the exception of the "en" language. I did the same locally (these aren't changes that were tracked in git) and the issue went away.

**Comment by kamsar** [comment]
Oh interesting so it was triggered by having a missing language in the database that was throwing the error?
