### ISSUE TITLE
w3p crash when using copy to or renaming item

### ISSUE THREAD

**Issue by Rclemens** [kamsar/Unicorn#222]
Hi, I think I'm having a bug or am doing something terribly wrong

We were using unicorn 2 and I've updated the solution to unicorn 3.3.2 (with SC 8.2 update 1) following the update steps in your blog. I've deleted the old serialization.config and adjusted the new configs. After that I could do a full serialization of the database. That went without any big issues

Now I see that sometimes when I edit or use the copy-to option my just w3p process crashes. Attaching this crash to my visual studio just tells me there is a nullref exception. The new or changed item is on disk, so that part works.

Any idea's what I could be doing wrong?

**Comment by kamsar** [comment]
Can you provide the stack trace of your exception?

**Comment by Rclemens** [comment]
Hi,

I'm getting this in the eventviewer:
`A Webhost unhandled exception occurred.
 Sender Information: System.AppDomain/2129745
 Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Unicorn.Data.DataProvider.UnicornDataProvider.RemoveItemFromCaches(IItemMetadata metadata, String databaseName)
   at Rainbow.Storage.SerializationFileSystemDataStore.<>c__DisplayClass23_0.<CreateTree>b__0(IItemMetadata metadata)
   at Rainbow.Storage.SerializationFileSystemTree.HandleDataItemChanged(String path, TreeWatcherChangeType changeType)
   at Rainbow.Storage.TreeWatcher.FlushEvents(Object ignored)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
 Process Name: w3wp
 Process ID: 6464`

**Comment by kamsar** [comment]
The relevant code is here https://github.com/kamsar/Unicorn/blob/master/src/Unicorn/Data/DataProvider/UnicornDataProvider.cs#L754

Are you using link db or search index update support?

I can see that there is an issue here at the very least in that the method should trap exceptions and log them (since it runs on an event handling thread, and as you could background exceptions terminate the app pool). I've definitely not seen this particular issue before.

You might also give it a try with the current Unicorn 4 prerelease version. It's basically ready to go and I've used it on production projects that are live, it's just a matter of making the time to do a proper release; Dlilithium is the only semi-experimental part and it's off by default :)

**Comment by kamsar** [comment]
Relevant catching and some speculative null checks have been added to Unicorn 4.0-pre09 which is on NuGet.

**Comment by Rclemens** [comment]
Hi @kamsar, upgrading to Unicorn 4.0-pre09 solved this problem for me. Thanks for your help
