### ISSUE TITLE
Getting "ArgumentException: An item with the same key has already been added" error when doing a Sync

### ISSUE THREAD

**Issue by eh-ssuryana** [kamsar/Unicorn#231]
Hi,

I have Sitecore.NET 7.5 (rev. 150212) and using unicorn ver: 3.3.2.

I was able successfully set up unicorn and run Re-serialize, but when I just run Sync immediately after Re-serialize  I am getting "ArgumentException: An item with the same key has already been added" error. 

I have not modified the yml file, and I am doing the Sync right after Re-serialize. and getting the error only for a few items and not all.

Any help would be appreciated.

Thanks.

**Comment by kamsar** [comment]
Please provide the full stack trace of the error.

**Comment by eh-ssuryana** [comment]
2017-06-08 09:06:48:01 INFO  [Unicorn]: My Site is being synced.
2017-06-08 09:06:48:02 WARN  All caches have been cleared. This can decrease performance considerably.
2017-06-08 09:06:53:51 ERROR ERROR: Some directories could not be loaded. (19 inner failures)
master:/sitecore/templates/Full/www-site-com/ArchitecturalElements/Page/Style Override/CSS Override (ce4af43d-980d-4e0c-84b6-90181f831acc)

master:/sitecore/templates/Full/www-site-com/ArchitecturalElements/Page/Style Override/Script Override (37f7441f-16a4-4156-b808-9276ffd39935)

master:/sitecore/content/www-site-com/home-full-site/pagedata (9bbde72b-aac1-4962-8b66-25d170b72b7e)

master:/sitecore/content/www-site-com/home-full-site/about/pagedata (1bc3ffc8-91b4-4e23-9890-b1fe0715dfd9)

master:/sitecore/content/www-site-com/home-full-site/pagedata/blockquoteandsprinkle (7199f509-1d22-42c6-a916-e23ecd0f18d7)

master:/sitecore/content/www-site-com/home-full-site/patient-resources/pagedata (17f544a1-2f00-4cde-89ec-103e5ee48393)

master:/sitecore/content/www-site-com/home-full-site/postmenopausal-osteoporosis/pagedata (4e87bc7e-7fab-47b0-8eb8-2296cb0b5c17)

master:/sitecore/content/www-site-com/home-full-site/about/site-treatment-plan/pagedata (3a6b9572-d955-47c6-9a94-9b57999559c8)

master:/sitecore/content/www-site-com/home-full-site/about/how-site-works/pagedata (58f5dce3-6bee-4aa7-96f7-1dcfdb21f2f0)

master:/sitecore/content/www-site-com/home-full-site/about/pagedata/blockquoteandsprinkle (125f3904-f785-4fc3-af77-7a439ffed28a)

master:/sitecore/content/www-site-com/home-full-site/about/possible-side-effects-site/pagedata (4301c6f9-10c6-4b26-80a4-933c19102258)

master:/sitecore/content/www-site-com/home-full-site/about/results-with-site/pagedata (38b7dad2-c3be-48a7-80ab-2bb462ba3593)

master:/sitecore/content/www-site-com/home-full-site/patient-resources/financial-assistance/pagedata (e5b581fb-7b5b-4e21-8972-57f88fd5da7d)

master:/sitecore/content/www-site-com/home-full-site/postmenopausal-osteoporosis/pagedata/bone-states (3c41e602-36a5-4d98-ac49-de6b7f1248d2)

master:/sitecore/content/www-site-com/home-full-site/about/site-treatment-plan/pagedata/blockquoteandsprinkle (664d7e4c-e46c-4388-87e9-5fcc35164533)

master:/sitecore/content/www-site-com/home-full-site/about/how-site-works/pagedata/blockquoteandsprinkle (0f97b2f1-6e90-45de-a3f1-e8f83bd3f3ee)

master:/sitecore/content/www-site-com/home-full-site/about/possible-side-effects-site/pagedata/blockquoteandsprinkle (e29f5064-df86-4c73-a0dc-27e4d32c6c6a)

master:/sitecore/content/www-site-com/home-full-site/about/results-with-site/pagedata/blockquoteandsprinkle (5ca11c11-8d0e-4111-9ca8-3673f2014ebd)

master:/sitecore/content/www-site-com/home-full-site/patient-resources/financial-assistance/pagedata/blockquoteandsprinkle (1a25ae5e-298f-4e22-a729-39468e608473) (Unicorn.DeserializationAggregateException)
at Unicorn.Loader.DeserializeFailureRetryer.RetryAll(ISourceDataStore sourceDataStore, Action`1 retrySingleItemAction, Action`1 retryTreeAction)
   at Unicorn.Loader.SerializationLoader.LoadAll(IItemData[] rootItemsData, IDeserializeFailureRetryer retryer, IConsistencyChecker consistencyChecker, Action`1 rootLoadedCallback)
   at Unicorn.SerializationHelper.SyncTree(IConfiguration configuration, Action`1 rootLoadedCallback, IItemData[] roots)
   at Unicorn.ControlPanel.Pipelines.UnicornControlPanelRequest.SyncVerb.Process(IProgressStatus progress, ILogger additionalLogger)

INNER EXCEPTION
master:/sitecore/templates/Full/www-site-com/ArchitecturalElements/Page/Style Override/CSS Override (ce4af43d-980d-4e0c-84b6-90181f831acc) (Rainbow.Storage.Sc.Deserialization.DeserializationException)
No stack trace available.
INNER EXCEPTION
An item with the same key has already been added. (System.ArgumentException)
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Rainbow.Diff.ItemComparer.CompareInternal(IItemData sourceItem, IItemData targetItem, Boolean abortOnChangeFound)
   at Unicorn.Evaluators.SerializedAsMasterEvaluator.ShouldUpdateExisting(IItemData sourceItem, IItemData targetItem, DeferredLogWriter`1 deferredUpdateLog)
   at Unicorn.Evaluators.SerializedAsMasterEvaluator.EvaluateUpdate(IItemData sourceItem, IItemData targetItem)
   at Unicorn.Loader.SerializationLoader.DoLoadItem(IItemData serializedItemData, IConsistencyChecker consistencyChecker)
   at Unicorn.Loader.DeserializeFailureRetryer.RetryAll(ISourceDataStore sourceDataStore, Action`1 retrySingleItemAction, Action`1 retryTreeAction)


INNER EXCEPTION
master:/sitecore/templates/Full/www-site-com/ArchitecturalElements/Page/Style Override/Script Override (37f7441f-16a4-4156-b808-9276ffd39935) (Rainbow.Storage.Sc.Deserialization.DeserializationException)
No stack trace available.
INNER EXCEPTION
An item with the same key has already been added. (System.ArgumentException)
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Rainbow.Diff.ItemComparer.CompareInternal(IItemData sourceItem, IItemData targetItem, Boolean abortOnChangeFound)
   at Unicorn.Evaluators.SerializedAsMasterEvaluator.ShouldUpdateExisting(IItemData sourceItem, IItemData targetItem, DeferredLogWriter`1 deferredUpdateLog)
   at Unicorn.Evaluators.SerializedAsMasterEvaluator.EvaluateUpdate(IItemData sourceItem, IItemData targetItem)
   at Unicorn.Loader.SerializationLoader.DoLoadItem(IItemData serializedItemData, IConsistencyChecker consistencyChecker)
   at Unicorn.Loader.DeserializeFailureRetryer.RetryAll(ISourceDataStore sourceDataStore, Action`1 retrySingleItemAction, Action`1 retryTreeAction)


INNER EXCEPTION
master:/sitecore/content/www-site-com/home-full-site/pagedata (9bbde72b-aac1-4962-8b66-25d170b72b7e) (Rainbow.Storage.Sc.Deserialization.DeserializationException)
No stack trace available.
INNER EXCEPTION
An item with the same key has already been added. (System.ArgumentException)
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Rainbow.Diff.ItemComparer.CompareInternal(IItemData sourceItem, IItemData targetItem, Boolean abortOnChangeFound)
   at Unicorn.Evaluators.SerializedAsMasterEvaluator.ShouldUpdateExisting(IItemData sourceItem, IItemData targetItem, DeferredLogWriter`1 deferredUpdateLog)
   at Unicorn.Evaluators.SerializedAsMasterEvaluator.EvaluateUpdate(IItemData sourceItem, IItemData targetItem)
   at Unicorn.Loader.SerializationLoader.DoLoadItem(IItemData serializedItemData, IConsistencyChecker consistencyChecker)
   at Unicorn.Loader.DeserializeFailureRetryer.RetryAll(ISourceDataStore sourceDataStore, Action`1 retrySingleItemAction, Action`1 retryTreeAction)


**NOTE:
1. Looks like it skipped majority of the items in templates folder**

**Comment by kamsar** [comment]
Based on the relevant code site, it looks like a bad merge might well have resulted in your YAML having two copies of the same language in the same file.

```
var sourceUnversioned = sourceItem.UnversionedFields.ToDictionary(value => value.Language.Name);
var targetUnversioned = targetItem.UnversionedFields.ToDictionary(value => value.Language.Name);
```
