### ISSUE TITLE
AppVirtualRootPath not being resolved correctly (Azure Web App / Unicorn 4.x)

### ISSUE THREAD

**Issue by markdebruijne** [kamsar/Unicorn#260]
**Do you want to request a *feature* or report a *bug*?**
A **bug**

**What is the current behavior?**
* Roles are not being synced (yml > Sitecore). It fails silently as - as we expect - the path with yml can't be resolved. https://github.com/kamsar/Unicorn/blob/master/src/Unicorn.Roles/Data/FilesystemRoleDataStore.cs#L33
* Creating a new role (matching the specified pattern) gives an error (Sitecore UI, dialog) and writes the following exception to the logs. Note that the path stated is not absolute. Probably on this line: https://github.com/kamsar/Unicorn/blob/master/src/Unicorn.Roles/Data/FilesystemRoleDataStore.cs#L48
```
2017-11-22T15:12:26  PID[9888] Error       5636 15:12:26 ERROR One or more exceptions occurred while processing the subscribers to the 'role:created' event.
Exception[1]: System.UnauthorizedAccessException 
Message[1]: Access to the path '\unicorn_serialization\Project\<masked>\roles\sitecore' is denied. 
Source[1]: mscorlib 
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at Unicorn.Roles.Data.FilesystemRoleDataStore.Save(IRoleData role)
   at Unicorn.Roles.Events.UnicornRolesEventHandler.RoleCreated(Object sender, EventArgs e)
   at Sitecore.Events.Event.EventSubscribers.RaiseEvent(String eventName, Object[] parameters, EventResult result)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
* Test on the Azure Web App running the same Sitecore and Unicorn versions, `XP0` package for example.
* Create a role configuration with a `physicalRootPath` starting with a `~` to specify the app relative root path. For example ```physicalRootPath="~/unicorn_serialization\Project\EnecoLiftUp\roles"``` . _We know we are not using the mainstream configuration in which .yml are being placed within `/App_Config/Unicorn` 😄_
* Create same `.yml` representing a couple of roles, matching the configured domain/pattern
* Run a sync on the Azure environment. Note that no roles are being synced, and that no errors are being thrown. However, in case the environment already contains roles that are matching the pattern, those roles will be removed as a result of the sync, which is expected behavior with `removeOrphans="true"`. This is a confirmation that the path can't be resolved, and there are no `.yml` being found to challenge the existing roles in the environment. 
* Withing the Sitecore Role Manager, create a new role matching the pattern of the role configuration. You'll receive the error as stated earlier. 

**What is the expected behavior?**
* Syncing roles based on an AppRelativeRootPath should work, or should throw an error (or logline in debug loglevel) that the configured path doesn't exist runtime.
* Reserialize of new roles should work with an AppRelativeRootPath. 

**Please mention your Sitecore version and Unicorn version.**
We are running the `XP0` and `XP` cloud packages for `Sitecore 8.2 rev. 170407 (update 3)`
```
  <package id="Configy" version="1.0.0" targetFramework="net46" />
  <package id="Kamsar.WebConsole" version="2.0.0" targetFramework="net46" />
  <package id="MicroCHAP" version="1.2.2.2" targetFramework="net46" />
  <package id="Rainbow" version="2.0.0" targetFramework="net46" />
  <package id="Rainbow.Core" version="2.0.0" targetFramework="net46" />
  <package id="Rainbow.Storage.Sc" version="2.0.0" targetFramework="net46" />
  <package id="Rainbow.Storage.Yaml" version="2.0.0" targetFramework="net46" />
  <package id="Unicorn" version="4.0.3" targetFramework="net46" />
  <package id="Unicorn.Core" version="4.0.3" targetFramework="net46" />
  <package id="Unicorn.Roles" version="4.0.3" targetFramework="net46" />
  <package id="Unicorn.Roles.Core" version="4.0.3" targetFramework="net46" />
```
We can confirm the bug isn't applicable while running the same Sitecore version with the `3.2.2` version of `Unicorn.Roles`

We expect this faulty behavior was introduced with this commit 467043f4f5dd626db1c6dc9004fe08ee85d6f27a . This as it worked in `v3.2.2` but didn't anymore in `v4.0.3`. And checking the source code in the repository, the faulty behavior is probably applicable to the syncing of Users. 

Could it be that `HostingEnvironment.IsHosted` or `HostingEnvironment.MapPath("~/")` or `AppDomain.CurrentDomain.BaseDirectory` isn't supported OR is returning an empty string `""`

_Workaround is available = specifying an absolute URL in the configurations on Azure `D:\home\site\wwwroot\unicorn_serialization`_

**Comment by kamsar** [comment]
Thanks for the detailed investigation. As you surmise I think this is a bug introduced in the commit you mentioned. ATM I'm waiting on a license I can use for maintenance so this will have to sit for a bit longer until I can test it and see about a fix. 

If someone has a chance to toss up a quick app service app to verify the behavior of `HostingEnvironment.IsHosted`, `HostingEnvironment.MapPath("~/")` and  `AppDomain.CurrentDomain.BaseDirectory` in app service, that would be really helpful.

**Comment by wolfeno** [comment]
Just checked ans it's
HostingEnvironment.IsHosted
True

HostingEnvironment.MapPath("~/")
D:\home\site\wwwroot\

AppDomain.CurrentDomain.BaseDirectory
D:\home\site\wwwroot\

**Comment by ahurynovich** [comment]
I had the same issue and the reason is in the Path.Combine method (called in Unicorn.Roles.Data.FilesystemRoleDataStore.InitializeRootPath method). Check this post: https://stackoverflow.com/questions/53102/why-does-path-combine-not-properly-concatenate-filenames-that-start-with-path-di/53118 - you will understand what I mean.

And my variables are:

1. HostingEnvironment.IsHosted: True
2. Both HostingEnvironment.MapPath and AppDomain.CurrentDomain.BaseDirectory: D:\home\site\wwwroot\
3. rootPath: ~/unicorn_serialization\Project\Dunea\serialization\Dunea.Website.Security.Roles

So when this line of code executes: return Path.Combine(hostingRoot, rootPath.Substring(1).Replace("/", Path.DirectorySeparatorChar.ToString()));
the second parameter has an absolute path thus retrurning the following results:
/unicorn_serialization\Project\Dunea\serialization\Dunea.Website.Security.Roles

So the directory with such a name does not exist and the roles cannot be read from the disk.
