### ISSUE TITLE
Items with the same name causes duplicate ID error

### ISSUE THREAD

**Issue by yannisgu** [kamsar/Unicorn#43]
Steps to reproduce:
1. Create a new item (e.g. a new folder named "Foo" under /sitecore/templates
2. Create a second item in the same folder and with the same name
3. Update the first item (e.g. create a new version in another language)
4. Perform Unicorn Sync

This will give an error similar to this:

    Duplicate serialized item IDs were detected ({10CDD112-2E0D-4B6B-B523-C5B7D37E70A7}) - this usually indicates corruption in the serialization provider data.
    Item 1: master:/sitecore/templates/Foo ({10CDD112-2E0D-4B6B-B523-C5B7D37E70A7})
    Item 1 ProviderId: d:\web\paygrounds\sc72rev14122610\Data\serialization\master\sitecore\templates\Foo.item
    Item 2: master:/sitecore/templates/Foo ({10CDD112-2E0D-4B6B-B523-C5B7D37E70A7})
    Item 2 ProviderId: d:\web\paygrounds\sc72rev14122610\Data\serialization\master\sitecore\templates\Foo_10CDD1122E0D4B6BB523C5B7D37E70A7.item
    ERROR: Consistency check failed - aborting loading. (Unicorn.Loader.ConsistencyException)
    at Unicorn.Loader.SerializationLoader.DoLoadItem(ISerializedItem serializedItem, IConsistencyChecker consistencyChecker)
    at Unicorn.Loader.SerializationLoader.LoadOneLevel(ISerializedReference root, IDeserializeFailureRetryer retryer, IConsistencyChecker consistencyChecker)
    at Unicorn.Loader.SerializationLoader.LoadTreeRecursive(ISerializedReference root, IDeserializeFailureRetryer retryer, IConsistencyChecker consistencyChecker)
    at Unicorn.Loader.SerializationLoader.LoadTree(ISerializedItem rootItem, IDeserializeFailureRetryer retryer, IConsistencyChecker consistencyChecker)
    at Unicorn.Loader.SerializationLoader.LoadAll(ISerializedItem[] rootItems, IDeserializeFailureRetryer retryer, IConsistencyChecker consistencyChecker, Action`1 rootLoadedCallback)
    at Unicorn.ControlPanel.SyncConsole.Process(IProgressStatus progress)

The problem is that there are 3 serialized items file:
* Foo.item contains the first item with the first version
* Foo_50D0D04345B34EC982F86DF15C5F8627.item contains the second item
* Foo_FC0AB770513F453EB0F41F742FDC3141.item contains again the first item but with both versions.

The problem is that Sitecores `PathUtils.GetDirectoryPath` returns a path without ID as long as there is only one item in the DB with the same path, but as soon as there are two items with the same path it will return a path with the GUID inside.

**Comment by kamsar** [comment]
This is a known issue, and unfortunately one that is not trivial to solve given the way Sitecore stores serialized item paths. At present, having items with the same name on the same path is not a supported scenario. If you must sync such items, serialize them using Sitecore serialization initially and manually serialize with Sitecore serialization if they are changed.

Other than a few core database things (dividers) I would generally regard items of the same name in the same path as also a content antipattern.

I'll leave this open as I do intend to look at resolving this in Unicorn 3.

**Comment by kamsar** [comment]
This will be solved in Unicorn 3 (via the new organization structure in Rainbow). I've got tests for this scenario.
