### ISSUE TITLE
If a path is included twice, a Unicorn.Loader.ConsistencyException is thrown

### ISSUE THREAD

**Issue by yannisgu** [kamsar/Unicorn#44]
Let's assume a include configuration like this:

```
  <predicate type="Unicorn.Predicates.SerializationPresetPredicate, Unicorn" singleInstance="true">
            <include database="core" path="/sitecore/content/Documents and settings/All users"/>
            <include database="core" path="/sitecore/content/Documents and settings/All users/Start menu" />
</predicate>
```

Serialization will work fine, however when performing a sync, this will throw an exception like:
```
2092 10:52:52 ERROR [Unicorn]: Duplicate serialized item IDs were detected ({B965ECE5-5879-4D8D-A6B1-4233D7D06B0F}) - this usually indicates corruption in the serialization provider data.<br>Item 1: core:/sitecore/content/Documents and settings/All users/Start menu ({B965ECE5-5879-4D8D-A6B1-4233D7D06B0F})<br> Item 1 ProviderId: Z:\work\9cb9e3c71f951d07\serialization\app\core\sitecore\content\Documents and settings\All users\Start menu.item
Item 2: core:/sitecore/content/Documents and settings/All users/Start menu ({B965ECE5-5879-4D8D-A6B1-4233D7D06B0F})
Item 2 ProviderId: Z:\work\9cb9e3c71f951d07\serialization\app\core\sitecore\content\Documents and settings\All users\Start menu.item
2092 10:52:52 ERROR ERROR: Consistency check failed - aborting loading. (Unicorn.Loader.ConsistencyException)
at Unicorn.Loader.SerializationLoader.DoLoadItem(ISerializedItem serializedItem, IConsistencyChecker consistencyChecker)
   at Unicorn.Loader.SerializationLoader.LoadTree(ISerializedItem rootItem, IDeserializeFailureRetryer retryer, IConsistencyChecker consistencyChecker)
   at Unicorn.Loader.SerializationLoader.LoadAll(ISerializedItem[] rootItems, IDeserializeFailureRetryer retryer, IConsistencyChecker consistencyChecker, Action`1 rootLoadedCallback)
   at Unicorn.ControlPanel.SyncConsole.Process(IProgressStatus progress)
```

Would be cool if the exception was clearer or even better if this case was just ignored.

**Comment by kamsar** [comment]
This is really a configuration syntax error, but a nicer error would be a decent idea. I'll consider it if I have time.

**Comment by kamsar** [comment]
Unicorn 3 will support this scenario, if you want to use it, because you have a tree per `<include>`
