### ISSUE TITLE
You cannot have a sparse serialized tree.

### ISSUE THREAD

**Issue by kvde** [kamsar/Unicorn#48]
After installing the lastest version https://www.nuget.org/packages/Unicorn/3.0.0-beta04 in a Sitecore 8 Update 5 website the following error occurs when starting the site.

Unicorn.aspx is also not accessible because of the error.

Unicorn configuration is default. In the data folder a Rainbow folder is automatically created.

Stacktrace from the Sitecore Log:

8616 19:18:09 ERROR Application error.
Exception: System.InvalidOperationException
Message: The parent item of /sitecore/system/Sites/scheduler was not serialized. You cannot have a sparse serialized tree.
Source: Rainbow
   at Rainbow.Storage.SerializationFileSystemTree.GetTargetPhysicalPath(IItemData item)
   at Rainbow.Storage.SerializationFileSystemTree.Save(IItemData item)
   at Unicorn.UnicornDataProvider.SaveItem(ItemDefinition itemDefinition, ItemChanges changes, CallContext context)
   at Unicorn.UnicornSqlServerDataProvider.SaveItem(ItemDefinition itemDefinition, ItemChanges changes, CallContext context)
   at Sitecore.Data.DataProviders.DataProvider.SaveItem(ItemDefinition item, ItemChanges changes, CallContext context, DataProviderCollection providers)
   at Sitecore.Data.DataSource.SaveItem(ID itemID, ItemChanges changes)
   at Sitecore.Data.Engines.EngineCommand`2.Execute()
   at Sitecore.Data.Engines.DataEngine.SaveItem(Item item)
   at Sitecore.Data.Managers.ItemProvider.SaveItem(Item item)
   at Sitecore.Data.Managers.PipelineBasedItemProvider.ExecuteAndReturnResult[TArgs,TResult](String pipelineName, String pipelineDomain, Func`1 pipelineArgsCreator, Func`1 fallbackResult)
   at Sitecore.Data.Managers.PipelineBasedItemProvider.SaveItem(Item item)
   at Sitecore.Data.Items.ItemEditing.AcceptChanges(Boolean updateStatistics, Boolean silent)
   at Sitecore.Data.Items.ItemEditing.EndEdit(Boolean updateStatistics, Boolean silent)
   at Sitecore.Shell.Framework.Sorting.SetSortorder(Item item, Int32 sortorder)
   at Sitecore.Shell.Framework.Sorting.MoveLast(Item[] items)
   at Sitecore.Sites.MultiSitesManager.ArrangeSitesContext()
   at Sitecore.Sites.MultiSitesManager.Process(HttpRequestArgs args)
   at (Object , Object[] )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Nexus.Web.HttpModule.(Object , EventArgs )
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by kvde** [comment]
I have resolved this issue. I had installed the MultipleSite Manager module.
That module was not configured correctly. After I fixed that Unicorn was working

**Comment by kamsar** [comment]
Sorry I was out on a business trip yesterday. You're right, it was the MSM. If you run across something like this in the future where something is saving an item you want to serialize, but have not yet, on startup you can disable the `Unicorn.DataProvider.config` temporarily and that should let you start up and get the item serialized, at which point the data provider can be turned back on.

**Comment by WizX20** [comment]
Hi, I'm sorry but I don't think this a a solution. I think Unicorn should pick up the moved item and serialize it no matter where it comes from.

**Comment by kamsar** [comment]
Not sure what you mean, this issue wasn't to do with moving items?
