### ISSUE TITLE
System.OutOfMemoryException during serialization of Media Library

### ISSUE THREAD

**Issue by JobiJoba** [kamsar/Unicorn#73]
Hey, 

i'm trying to serialize my media library which is quite big and so i made a configuration specific for it.

During the serialization i've the following error : 

ERROR: One or more errors occurred. (System.AggregateException)
at Unicorn.SerializationHelper.DumpTreeInternal(IItemData root, IPredicate predicate, ITargetDataStore serializationStore, ISourceDataStore sourceDataStore, ILogger logger) 
at Unicorn.SerializationHelper.DumpTree(IItemData item, IConfiguration configuration) 
at Unicorn.ControlPanel.ReserializeConsole.Process(IProgressStatus progress)
Error while writing SFS item C:\Projects\XXX\Unicorn\XXXX\xxxxx xxxxx\media library\xxxxxxxxxxxxx xxxxx\2014\XXX\xx xxxx_xxxxxxx.yml (Rainbow.Storage.SfsWriteException)
at Rainbow.Storage.SerializationFileSystemTree.WriteItem(IItemData item, String path) 
at Rainbow.Storage.SerializationFileSystemTree.Save(IItemData item) 
at Rainbow.Storage.SerializationFileSystemDataStore.Save(IItemData item) 
at Unicorn.Data.ConfigurationDataStore.Save(IItemData item) 
at Unicorn.SerializationHelper.DumpItemInternal(IItemData item, IPredicate predicate, ITargetDataStore targetDataStore) 
at Unicorn.SerializationHelper.<>c__DisplayClass5.b__4()
Exception of type 'System.OutOfMemoryException' was thrown. (System.OutOfMemoryException)
at System.Text.StringBuilder.ToString() 
at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args) 
at System.IO.TextWriter.WriteLine(String format, Object arg0, Object arg1) 
at Rainbow.Storage.Yaml.YamlWriter.WriteMapInternal(String key, String value) 
at Rainbow.Storage.Yaml.YamlWriter.WriteMap(String key, String value) 
at Rainbow.Storage.Yaml.OutputModel.YamlFieldValue.WriteYaml(YamlWriter writer) 
at Rainbow.Storage.Yaml.OutputModel.YamlItem.WriteYaml(YamlWriter writer) 
at Rainbow.Storage.Yaml.YamlSerializationFormatter.WriteSerializedItem(IItemData itemData, Stream outputStream) 
at Rainbow.Storage.SerializationFileSystemTree.WriteItem(IItemData item, String path)

This happens on dev environment (still not on prod or on a server)

I've changed in the rainbow.config to that 

	<setting name="Rainbow.SFS.SerializationFolderPathMaxLength" value="66" />
        <setting name="Rainbow.SFS.MaxItemNameLengthBeforeTruncation" value="100" />

The rest is default stuff. The size of the items on the ML are on average 1mb - 200mb. 
I've no problems with my others config (but it's more for template)

Do you have an idea ? Can i give you more information ?

**Comment by kamsar** [comment]
I'm guessing that it gets a number of items serialized before this occurs, roughly how many and what's the file size on disk of those?

How much RAM do you have?

**Comment by JobiJoba** [comment]
Hey, 

Yes it crash after 1893 files this time for +- 1.76 GB. 

I've 8GB of RAM (poor me :P)

**Comment by kamsar** [comment]
Do you have `useDataCache=true` on your target data store? Are you using Transparent Sync?

Try disabling the Unicorn.DataProvider.config` while serializing to see if that narrows down the problem.

**Comment by kamsar** [comment]
Closing due to inactivity
