### ISSUE TITLE
Possible issue when restoring a moved item

### ISSUE THREAD

**Issue by kamsar** [kamsar/Unicorn#81]
Stack:
```
master:/sitecore/templates/xxx/Site Structure/Page Components/Social Meta Information/Social Meta Information/social thumnail (9299754f-97dd-4e4d-8649-8860fb2d4f33) (Rainbow.Storage.Sc.Deserialization.DeserializationException)
No stack trace available.
INNER EXCEPTION
Key cannot be null.
Parameter name: key (System.ArgumentNullException)
at System.Collections.Hashtable.get_Item(Object key)
  at Sitecore.Caching.Cache.DoGetEntry(Object key, Boolean updateAccessed)
  at Sitecore.Caching.Cache.GetValue(Object key)
  at Sitecore.Caching.DataCache.GetItemInformation(ID itemID)
  at Sitecore.Data.DataSource.GetItemInformation(ID itemID)
  at Sitecore.Data.DataSource.MoveItem(ID itemID, ID destinationID)
  at Sitecore.Nexus.Data.DataCommands.MoveItemCommand.Execute(Item , Item )
  at Sitecore.Nexus.Data.NexusDataApi.MoveItem(Item item, Item destination)
  at Sitecore.Data.Engines.DataCommands.MoveItemCommand.DoExecute()
  at Sitecore.Data.Engines.EngineCommand`2.Execute()
  at Sitecore.Data.Managers.ItemProvider.MoveItem(Item item, Item destination, SecurityCheck securityCheck)
  at Sitecore.Data.Managers.PipelineBasedItemProvider.<>c__DisplayClass43.<MoveItem>b__42()
  at Sitecore.Data.Managers.PipelineBasedItemProvider.ExecuteAndReturnResult[TArgs,TResult](String pipelineName, String pipelineDomain, Func`1 pipelineArgsCreator, Func`1 fallbackResult)
  at Sitecore.Data.Managers.PipelineBasedItemProvider.MoveItem(Item item, Item destination, SecurityCheck securityCheck)
  at Sitecore.Data.Managers.ItemManager.MoveItem(Item item, Item destination, SecurityCheck securityCheck)
  at Sitecore.Data.Managers.ItemManager.MoveItem(Item item, Item destination)
  at Sitecore.Data.Items.Item.MoveTo(Item destination)
  at Rainbow.Storage.Sc.Deserialization.DefaultDeserializer.GetOrCreateTargetItem(IItemData serializedItemData, Boolean& newItemWasCreated)
  at Rainbow.Storage.Sc.Deserialization.DefaultDeserializer.Deserialize(IItemData serializedItemData)
  at Rainbow.Storage.Sc.SitecoreDataStore.Save(IItemData item)
  at Unicorn.Data.ConfigurationDataStore.Save(IItemData item)
  at Unicorn.Evaluators.SerializedAsMasterEvaluator.EvaluateUpdate(IItemData sourceItem, IItemData targetItem)
  at Unicorn.Loader.SerializationLoader.DoLoadItem(IItemData serializedItemData, IConsistencyChecker consistencyChecker)
  at Unicorn.Loader.SerializationLoader.<LoadAll>b__0(IItemData item)
  at Unicorn.Loader.DeserializeFailureRetryer.RetryAll(ISourceDataStore sourceDataStore, Action`1 retrySingleItemAction, Action`1 retryTreeAction)
```

@kamsar
and lemme guess, the error disappeared later?

@divamatrix
it syncs them just fine
and yeah.. i've had some other issues with synthesis... so i think i did a sync tree earlier before when i tried to dupe it for you earlier, and it was fine afterwards
but i just updated from an external library which has a script that will automatically recreates all the .yml files again.. and when i just did a sync it came up again.   is it just that the files that are getting updated are not generated correctly?

@kamsar
well it appears that based on the stack trace, it's finding an item which has a different parent id serialized than it does in the local database
so it tries to move it while deserializing
and then somehow blows up way down in the Sitecore caches
I'd guess somehow it's being sent a null ID
idk if a unicorn bug or Sitecore but I'll open a ticket on github about it

Let's test syncing items to new parent IDs and see if we can reproduce anything here.

**Comment by divamatrix** [comment]
further research on this has come up with several things:

content is showing up if i'm in the sitecore backend viewing it.. it says its controlled by unicorn but then it says that it's not in the sitecore database.  If I try to update tree/item or sync, it doesn't add things and sometimes throws an error

Viewing the sitecore database after a sync had very few actual updates. 

Unicorn logs include instances where some items show 2 different paths for the item, with the database path showing the old location and the absolute file path being correct.  For example:
master:/sitecore/templates/HRP-Base/Site Structure/Footer/Footer Link Group/Group Data/Links (f913a9d4-44d7-44a5-8042-95ceee4f6f09)
C:\Project\Platform.Unicorn\HRP-Base\HRP-Base\Navigation\Footer\Footer Link Group\Group Data\Links.yml
> ArgumentNullException: Key cannot be null. Parameter name: key

It appears that this may be related to moving items in the sitecore backend not updating the path on the yaml file correctly (i.e. dragging an item and it's subtree to a new location rather than using the "Move To" functionality).  If items are moved using drag and drop (this needs further testing to confirm that this is exactly what is happening), but it appears that it does NOT update the path on the yaml file.  Going to the item where it or it's subitems are throwing errors, if you choose "Move to" and chose the right location.. it adjusts the path correctly and does so on the child yaml files.  Then it's simply a matter of "Update tree" on the item and it will update the item and the subtree into Sitecore correctly.

**Comment by divamatrix** [comment]
Just an FYI, I think the issue with renaming ancestor items and it deleting child items is definitely related to the issue with moved items. If the path of the a parent item changes, (depending on how the item path/name is updated) it would often seem to orphan the subitems and delete the physical files. It feels like the sync is happening at the same time that it should be updating child items and maybe the sync happens before items are updated correctly and it ends up wiping them out.  I definitely had this happen in trying to track down my sync issues.  

Also, an odd thing that I forgot to mention is that I found that even though the folder permissions were set right with inheritance turned on, after syncing with Git, it seems like the folder permissions didn't inherit and there were some permission denied that I could see in the logs.  Once I specifically granted the app pool identity access (Network Service) and reapplied the permissions on the data source folder, it helped clear up some of the errors.

**Comment by kamsar** [comment]
This should be fixed by the mentioned commit in Rainbow above, as well as our discussion on Slack earlier about how copying in new YAML files without purging orphans will result in corruption (orphans being moved or deleted items)

**Comment by kamsar** [comment]
Rainbow 1.0.2-beta01 has been pushed to NuGet. Please update to it and verify that it fixes your problems.
