### ISSUE TITLE
Situation in which overlength path may be created

### ISSUE THREAD

**Issue by kamsar** [kamsar/Unicorn#91]
It looks like this particular case, a path that is too long is being created. Let's figure out why.

```
ERROR: One or more errors occurred. (System.AggregateException)
at Unicorn.SerializationHelper.DumpTreeInternal(IItemData root, IPredicate predicate, ITargetDataStore serializationStore, ISourceDataStore sourceDataStore, ILogger logger) 
at Unicorn.SerializationHelper.DumpTree(IItemData item, IConfiguration[] configurations) 
at Unicorn.ControlPanel.ReserializeConsole.Process(IProgressStatus progress)
Error while writing SFS item C:\tfs\Phoenix\ActiveCommerceCart\Sandbox\Website\app_data\Unicorn\BaseConfig\system\f9bb991c-6de2-4f42-bd70-f7d4a7d3140b\The type 0 was not mapped Check that the type has not been explicitly excluded by using the Ign_5dc8c7f0-a8ef-458e-82fd-945434d88125.yml (Rainbow.Storage.SfsWriteException)
at Rainbow.Storage.SerializationFileSystemTree.WriteItem(IItemData item, String path) 
at Unicorn.SerializationHelper.DumpItemInternal(IItemData item, IPredicate predicate, ITargetDataStore targetDataStore) 
at Unicorn.SerializationHelper.<>c__DisplayClass5.b__4()
The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters. (System.IO.PathTooLongException)
at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths) 
at System.IO.Path.GetDirectoryName(String path) 
at Rainbow.Storage.SerializationFileSystemTree.WriteItem(IItemData item, String path)
```

**Comment by kamsar** [comment]
Fixed by https://github.com/kamsar/Rainbow/commit/921e22c55e56c0094a4bdd329e18e607beb0c287, which alters the default Rainbow settings to avoid this problem.

Specifically this was caused by an item that was longer than the old default of 100 char max name length, that was also placed into a loopback folder. So the calculations for max name length, which assumed needing only space for one GUID, actually was too long. 100 chars is way too long of an allowed name length.

So the new default max is 30, and the expected max base path goes from 90 to 110, as I've had to up that on nearly every project so far.
